version: "3.8"
services:
  write-db:
    image: postgres
    restart: always
    ports:
      - "${DATABASE_PORT}:5432"
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
  read-db:
    image: mongo
    restart: always
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_DATABASE="vf-read-db"
  event-store:
    image: mongo:6.0.4
    restart: always
    ports:
      - "27018:27017"
    environment:
      - MONGO_INITDB_DATABASE="vf-event-store"
    command: mongod --replSet vf-event-store-repl-set
    volumes:
      - ./script/events-store-mongoinit.js:/docker-entrypoint-initdb.d/mong-init.js:ro
